fix state manager (#50)
- refactor state
- add debug panel
- fix tracestate
- context storage and debug panel under settings


This is break currently, but with this refactor i expect to fix multiple
issues related to stata manager including
#44 and one that was reported today `Error updating dynamic rules:
Error: Rule with id 1 does not have a unique ID.`

I think that refactor should improve the speed a little bit cause it
will prevent some duplicate calls that are triggered on the service
worker